#!/usr/bin/env node
"use strict";

/**
 * Generates frontend/config.js from environment variables.
 *
 * Source of values (later wins):
 *   1. frontend/.env (if present)
 *   2. process.env (Vercel injects its Project Environment Variables here)
 *
 * Run locally: `npm run build` (from frontend/).
 * Run on Vercel: set the Build Command to `node scripts/build-config.js`.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ENV_FILE = path.join(ROOT, ".env");
const OUT_FILE = path.join(ROOT, "config.js");

// Minimal .env parser — no dotenv dependency needed.
function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const out = {};
  for (const raw of fs.readFileSync(filePath, "utf8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

const fileEnv = loadEnvFile(ENV_FILE);
const merged = { ...fileEnv, ...process.env };

const apiBase = merged.MOMAS_API_BASE ?? "http://localhost:5050";
const refreshMs = parseInt(merged.MOMAS_REFRESH_MS ?? "300000", 10);
const maxMarkers = parseInt(merged.MOMAS_MAX_MARKERS ?? "500", 10);

const banner = `// AUTO-GENERATED by scripts/build-config.js — do not edit by hand.
// Source: frontend/.env and process.env at build time.
// Generated: ${new Date().toISOString()}`;

const body = `window.MOMAS_CONFIG = ${JSON.stringify({ apiBase, refreshMs, maxMarkers }, null, 2)};
`;

fs.writeFileSync(OUT_FILE, `${banner}\n${body}`);
console.log(
  `[build-config] wrote ${path.relative(ROOT, OUT_FILE)} (apiBase=${apiBase})`,
);
